### ISSUE TITLE
Qusetions about building

### ISSUE THREAD

**Issue by magojohnji** [LowTension/android_kernel_xiaomi_sm8475#3]
I am not good at building Linux kernels, so I have no idea what clang version I should use and what extra commands I need to add.
Can you tell me or add a build script?
And what's the difference between `main` branch and `staging` branch?
Thank you very much.

**Comment by Rofikkernel** [comment]
ok i try to help
staging is branch where is hold all you changes before merged or added to main (it can be rejected)

to see clang version goto Google aosp Clang it released based android version, but mostly i see right now them using clang 12.0.5

**Comment by Gosth15** [comment]
Well currently the dev is using Google Clang 17.0.4 (r498229b)
As for the commands, wait for me to respond or if you authorize me, I will provide them to you.
- Greetings.

**Comment by magojohnji** [comment]
> Well currently the dev is using Google Clang 17.0.4 (r498229b) As for the commands, wait for me to respond or if you authorize me, I will provide them to you.
> 
> * Greetings.

Thank you for replying. It seems that you can successfully build the kernel. I don't know what parameters are required to compile with `make`. Let me know if you'd like to. Thanks.
